Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The name of the environment being deployed.

Resources:
  markdowntable:
    Metadata:
      'aws:copilot:description': 'An Amazon DynamoDB table for markdown-table'
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${App}-${Env}-markdown-table
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: ID
          KeyType: HASH

Outputs:
  markdowntableName:
    Description: "The name of this DynamoDB table."
    Value: !Ref markdowntable
    Export: 
      Name: !Sub ${App}-${Env}-markdowntableTableName
  markdowntableDynamoDBTableARN:
    Description: "The ARN of the markdown-table DynamoDB table."
    Value: !GetAtt markdowntable.Arn
    Export: 
      Name: !Sub ${App}-${Env}-markdowntableTableArn
